import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "FAQ | The BRAIN Center",
  description:
    "Frequently asked questions about membership, projects, intellectual property, and Industry Advisory Board participation in the BRAIN Center.",
};

type FaqItemProps = {
  question: string;
  children: React.ReactNode;
};

function FaqItem({ question, children }: FaqItemProps) {
  return (
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
      <h2 className="text-lg font-semibold tracking-tight text-slate-900">
        {question}
      </h2>
      <div className="mt-3 space-y-2 text-sm leading-relaxed text-slate-700">
        {children}
      </div>
    </section>
  );
}

export default function QAPage() {
  return (
    <main className="bg-white">
      <div className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8">
        {/* Page header */}
        <header className="mb-10 border-b border-slate-200 pb-6">
          <p className="text-xs font-semibold uppercase tracking-[0.25em] text-teal-600">
            Membership &amp; Governance
          </p>
          <h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-900 sm:text-4xl">
            FAQ
          </h1>
          <p className="mt-3 max-w-3xl text-sm leading-relaxed text-slate-700">
            Answers to common questions about the NSF IUCRC BRAIN Center,
            including membership, benefits, intellectual property, and Industry
            Advisory Board responsibilities.
          </p>
        </header>

        <div className="space-y-8">
          <FaqItem question="What is an IUCRC?">
            <p>
              An Industry&ndash;University Cooperative Research Center (IUCRC)
              is an NSF-funded center that supports industry-relevant,
              pre-competitive research through long-term partnerships between
              universities, industry, and government agencies. IUCRCs pool
              member resources to support collaborative research, train the next
              generation of talent, and accelerate technology transfer.
            </p>
          </FaqItem>

          <FaqItem question="What are the different membership levels and associated costs?">
            <p>
              Industry members typically join as full members at a standard
              annual fee (for example, around $50,000 per year). Foundation and
              non-profit memberships may be available at a reduced rate. Exact
              levels and current rates are set by the Center and may change over
              time.
            </p>
            <p>
              For the most up-to-date membership options and pricing, please
              contact the Center directly using the information at the bottom of
              this page.
            </p>
          </FaqItem>

          <FaqItem question="How long should I plan on being a member of the Center?">
            <p>
              Membership is renewed annually, but the Center is designed as a
              long-term partnership. Many projects span multiple years, and
              companies often remain members to follow their research portfolio,
              recruit students, and continue shaping the research roadmap.
            </p>
            <p>
              If your organization plans to terminate membership, advance notice
              is requested so that existing commitments and projects can be
              managed responsibly.
            </p>
          </FaqItem>

          <FaqItem question="Who are the current BRAIN Center members?">
            <p>
              The Center includes university sites and a diverse set of industry
              partners from medical device companies, technology firms,
              hospitals, and other organizations interested in neurotechnology.
            </p>
            <p>
              A current list of member organizations is maintained on our
              Membership page.
            </p>
            <p>
              {/* Adjust this route to match however you wire membership in the new site */}
              <a
                href="/membership"
                className="font-medium text-teal-700 underline underline-offset-2"
              >
                View current BRAIN Center members
              </a>
              .
            </p>
          </FaqItem>

          <FaqItem question="What are the membership benefits of the BRAIN Center?">
            <ul className="list-disc space-y-2 pl-5">
              <li>
                Voting rights to help select and steer pre-competitive research
                projects.
              </li>
              <li>
                Access to research results, data, and prototypes generated by
                Center projects.
              </li>
              <li>
                Opportunities to work closely with faculty, students, and other
                member organizations.
              </li>
              <li>
                Early visibility into emerging neurotechnology standards and
                regulatory science.
              </li>
              <li>
                Talent pipeline and recruiting opportunities for highly skilled
                students and trainees.
              </li>
            </ul>
          </FaqItem>

          <FaqItem question="How does Intellectual Property work within the Center?">
            <p>
              Universities retain the right to publish results in scientific and
              engineering venues after allowing sufficient time for invention
              disclosure and IP protection. Inventions arising from Center
              projects are disclosed through each university&apos;s technology
              transfer office.
            </p>
            <p>
              BRAIN Center member companies may be eligible for nonexclusive,
              royalty-free licenses or, in some cases, to negotiate
              royalty-bearing exclusive licenses according to the Center&apos;s
              IP policies and the relevant university office of technology
              transfer.
            </p>
            <p>
              More details are provided on the{" "}
              <a
                href="/about/intellectual-property"
                className="font-medium text-teal-700 underline underline-offset-2"
              >
                Intellectual Property
              </a>{" "}
              page.
            </p>
          </FaqItem>

          <FaqItem question="When is the best time to sign up for membership?">
            <p>
              New members can typically join at any time during the year.
              However, it is helpful to join in advance of Industry Advisory
              Board (IAB) meetings so that your organization can participate in
              project reviews, voting, and planning for the next funding cycle.
            </p>
          </FaqItem>

          <FaqItem question="When is the next Industry Advisory Board (IAB) meeting?">
            <p>
              The BRAIN Center holds IAB meetings annually, with additional
              virtual check-ins as needed. Dates and locations vary by year.
            </p>
            <p>
              For current IAB meeting information, please contact the Program
              Manager or refer to Center communications sent to member
              organizations.
            </p>
          </FaqItem>

          <FaqItem question="How are research projects selected?">
            <p>
              Faculty and investigators propose projects that align with the
              Center&apos;s mission. These proposals are presented to the
              Industry Advisory Board, which provides feedback, ranks projects,
              and votes on which projects to fund with Center resources.
            </p>
            <p>
              Projects are evaluated on scientific merit, relevance to member
              needs, feasibility, and potential impact. Highly ranked projects
              are prioritized for funding, while other promising ideas may be
              refined and resubmitted in future cycles.
            </p>
          </FaqItem>

          <FaqItem question="What are my responsibilities as an Industry Advisory Board (IAB) member?">
            <ul className="list-disc space-y-2 pl-5">
              <li>
                Participate in IAB meetings and provide feedback on project
                proposals and Center activities.
              </li>
              <li>
                Help identify industry needs, use cases, and standards-related
                challenges that can guide future research.
              </li>
              <li>
                Review project progress and outcomes, and provide input on
                continuation or redirection.
              </li>
              <li>
                Support technology transition, collaborations, and, when
                relevant, licensing or commercialization efforts.
              </li>
            </ul>
          </FaqItem>

          <FaqItem question="How do I become a member?">
            <p>
              To explore membership, please contact the Center leadership team.
              They can discuss membership levels, benefits, and the process for
              joining the IAB.
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>
                Center Director (University of Houston):{" "}
                <a
                  href="mailto:jlcontreras-vidal@uh.edu"
                  className="font-medium text-teal-700 underline underline-offset-2"
                >
                  jlcontreras-vidal@uh.edu
                </a>
              </li>
              <li>
                Program Management / Membership Inquiries:{" "}
                <a
                  href="mailto:brain@uh.edu"
                  className="font-medium text-teal-700 underline underline-offset-2"
                >
                  brain@uh.edu
                </a>
              </li>
            </ul>
          </FaqItem>
        </div>
      </div>
    </main>
  );
}